version: '3.2'
#========================================
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    tty: true # 나중에 지울 것.
    expose:
      - "3306"
    #WordPress Database를 포함하는 볼륨
    volumes:
      - type: bind
        source: /home/gshim/data/db_volume
        target: /var/lib/mysql
      # - type: volume
      #   source: db_volume
      #   target: /home/gshim/data
    env_file:
      - ./.env
    networks:
      - intra
  #========================================
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    depends_on:
    - mariadb
    expose:
      - "9000"
    volumes:
      - type: bind
        source: /home/gshim/data/wp_volume
        target: /var/www/html
      # - type: volume
      #   source: wp_volume
      #   target: /home/gshim/data
    env_file:
      - ./.env
    networks:
      - intra
  #========================================
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/gshim/data/wp_volume
        target: /var/www/html
      # - type: volume
      #   source: wp_volume
      #   target: /var/www/html
    env_file:
      - ./.env
    networks:
      - intra
#========================================
volumes:
  db_volume:
  wp_volume:
networks:
  intra:
    driver: bridge
