version: '3.2'
#========================================
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    tty: true
    expose:
      - "3306"
    #WordPress Database를 포함하는 볼륨1
    volumes:
    #   - type: bind
    #     source: ./somedir
    #     target: /somedir
      - type: volume
        source: db_volume
        target: /home/gshim/data
    networks:
      - intra
  #========================================
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
    - mariadb
    expose:
      - "9000"
    #tty: true
    volumes:
      # - type: bind
      #   source: ./somedir
      #   target: /somedir
      - type: volume
        source: wordpress_volume
        target: /home/gshim/data
    env_file:
      - ./.env
    networks:
      - intra
  #========================================
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      # - type: bind
      #   source: ./somedir
      #   target: /somedir
      - type: volume
        source: wordpress_volume
        target: /var/www/html
    networks:
      - intra
#========================================
volumes:
  db_volume:
  wordpress_volume:
networks:
  intra:
    driver: bridge
