# ===========================
# ╦ ╦╔═╗╦═╗╔╦╗╔═╗╦═╗╔═╗╔═╗╔═╗
# ║║║║ ║╠╦╝ ║║╠═╝╠╦╝║╣ ╚═╗╚═╗
# ╚╩╝╚═╝╩╚══╩╝╩  ╩╚═╚═╝╚═╝╚═╝
# ===========================

FROM alpine:3.14

#RUN : 이미지를 생성할 때 실행할 코드를 지정한다. ex)패키지 설치 or 파일권한변경
RUN apk update && apk upgrade
RUN apk add tini
RUN apk add php-common php-fpm php-mysqli php7-phar php7-json php7-iconv
RUN apk add curl

# for debug
RUN apk add mariadb-client bash

COPY ./tools/wordpress_start.sh /
COPY ./tools/wordpress_conf.sh /
COPY ./www.conf /
RUN chmod +x wordpress_start.sh wordpress_conf.sh

EXPOSE 9000

ENTRYPOINT ["/sbin/tini", "--", "./wordpress_start.sh"];

CMD ["php-fpm7", "-F"]

